# -*- coding: utf-8 -*-
"""mosecoparse.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uwh3wO8S2Ar98CkAW3ZC35HKdWGtiv57
"""

import requests
import json
import pandas as pd
import os.path
from os import makedirs
import sys

def get_elements():
  """Получаем данные о том, по каким показателям есть информация на карте

  Returns:
    dataframe: Elements used for mapping
  """
  r = requests.get(
      "https://mosecom.mos.ru/wp-content/themes/moseco/map/elements.php?locale=ru_RU&mapType=air"
  )
  answer = r.json()
  # Initial response is nested — [[]]
  flat_answer = answer[0]
  elements = pd.DataFrame.from_dict(flat_answer)
  return elements

# elements = get_elements()
# display(elements)

def get_stations(element):
  """Получаем данные обо всех станциях
  
  Args:
    element (str): An element name from the elements dataframe

  Returns:
    dataframe: All stations used on the map
  """
  r = requests.post(
        "https://mosecom.mos.ru/wp-content/themes/moseco/map/stations-new.php",
        data={"element": element}
      )
  answer = r.json()
  onstations = pd.DataFrame.from_dict(answer.get("able"))
  offstations = pd.DataFrame.from_dict(answer.get("disable"))
  allstations = pd.concat([onstations, offstations])
  allstations_clean = allstations[["stationname", "address", "longitude", "latitude", "pageLink"]].loc[allstations["longitude"] != 0].reset_index(drop=True)
  return allstations_clean
  
  

# stations = get_stations(elements["name"].iloc[0])
# stations.to_csv("stations.csv", index=False)
# display(stations)

def get_station_data(station_name, folder='.', gettime=False):
  """Получаем данные по станции и присоединяем их к соответствующему csv файлу
  
  Args:
    station_name (str): A station's name from the stations dataframe
    folder (str): Path to store a file
    gettime (bool): Do we get only observation time?

  Returns:
    dataframe: All obervations in the station at this hour
  """
  r = requests.post(
      "https://mosecom.mos.ru/wp-content/themes/moseco/map/station-popup.php",
      data={"station_name": station_name}
  )
  answer = r.json()
  if not answer:
    print(f"На станции {station_name} наблюдения не выполнялись")
    return
  clean_answer = answer['parameters']
  df = pd.DataFrame.from_dict(clean_answer)
  observation_time = df['dateTime'].iloc[0]
  if gettime:
    return observation_time
  tdf = df.transpose()
  # Get columns' names from row
  tdf.columns = tdf.loc['parametername']
  tdf['dateTime'] = observation_time
  tdf['station'] = station_name
  # Get one row as dataframe (use extra brackets for it) to write it as a row
  tdf_clean = tdf.loc[['modifyav']]

  filename = os.path.join(folder, f'{station_name}.csv')
  makedirs(folder, exist_ok=True)
  if os.path.isfile(filename):  # проверяем, существует ли файл
    with open(filename, encoding="utf-8") as f:
      tdf_old_length = sum(1 for line in f) - 1  # -1 is header line
    # читаем последнюю строку файла
    tdf_old_lastline = pd.read_csv(filename, skiprows=range(1, tdf_old_length))
    # сравниваем дату и время в последней строке с вновь полученными данными
    if tdf_old_lastline['dateTime'].iloc[0] == tdf_clean['dateTime'].iloc[0]:
      # если одинаковые, сообщаем пользователю
      print(f"Для станции {station_name} новых данных нет")
      return tdf_clean
    tdf_clean.to_csv(filename, mode='a', index=False, header=False)

  else:
    tdf_clean.to_csv(filename, mode='w', index=False, header=True)
  return tdf_clean

# display(get_station_data(stations["stationname"].iloc[12]))

def get_data(datafolder='.'):
  """Получаем данные по всем станциям и присоединяем их к соответствующему csv файлу

  Args:
    station_name (str): A station's name from the stations dataframe
    datafolder (str): Folder to store files
  
  Returns:
    str: DateTime of the observations
  """
  elements = get_elements()
  stations = get_stations(elements.name.iloc[0])
  makedirs(datafolder, exist_ok=True)
  stations_path = os.path.join(folder, "stations.csv")
  if not os.path.isfile(stations_path):
    stations.to_csv(stations_path, index=False)
  stations_names = stations['stationname']  # This is Series (1 dimension)
  observation_time = get_station_data(stations_names.iloc[0], gettime=True)
  stations_names.apply(lambda station_name: get_station_data(station_name, folder=datafolder))
  return observation_time

# observation_time = get_data()
# print(f"Загружены данные за данный час: {observation_time}")

if __name__ == "__main__":
  folder = os.path.normpath(sys.argv[1])
  observation_time = get_data(folder)
  print(f"Получены данные за данный час: {observation_time}. Сохранены в {folder}")